# Generated by Django 4.2.7 on 2026-02-07 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, help_text='Daily ROI %', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('pay_on_monday', models.BooleanField(default=True, verbose_name='پرداخت در دوشنبه')),
                ('pay_on_tuesday', models.BooleanField(default=True, verbose_name='پرداخت در سه\u200cشنبه')),
                ('pay_on_wednesday', models.BooleanField(default=True, verbose_name='پرداخت در چهارشنبه')),
                ('pay_on_thursday', models.BooleanField(default=True, verbose_name='پرداخت در پنج\u200cشنبه')),
                ('pay_on_friday', models.BooleanField(default=True, verbose_name='پرداخت در جمعه')),
                ('pay_on_saturday', models.BooleanField(default=True, verbose_name='پرداخت در شنبه')),
                ('pay_on_sunday', models.BooleanField(default=True, verbose_name='پرداخت در یکشنبه')),
                ('max_total_return_percent', models.DecimalField(decimal_places=2, default=250.0, help_text='حداکثر درصدی که کاربر می\u200cتواند از سرمایه خود برداشت کند (مثلا 250 درصد). بعد از این حد، پلن غیرفعال می\u200cشود.', max_digits=6, verbose_name='سقف کل برداشت (درصد)')),
                ('binary_retention_days', models.IntegerField(default=30, help_text='مدت زمانی که حجم سمت قوی بدون تعادل باقی می\u200cماند و پس از آن منقضی می\u200cشود.', verbose_name='مدت ذخیره حجم پای بلند (روز)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Level Number (1, 2, ...)', unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=3, help_text='Direct Invest Commission % (e.g. 5.000)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Referral Level',
                'verbose_name_plural': 'Referral Levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(default='standard', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Initial Amount')),
                ('reinvested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reinvested Capital')),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('total_profit_earned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed (Time Expired)'), ('capped', 'Completed (Max Cap Reached)'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
