# Generated by Django 4.2.7 on 2026-02-07 18:57

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, help_text='مثال: 09123456789', max_length=15, null=True, unique=True, verbose_name='شماره موبایل')),
                ('referral_code', models.CharField(blank=True, help_text='کدی که این کاربر برای دعوت دیگران استفاده می\u200cکند (فقط بعد از سرمایه\u200cگذاری تولید می\u200cشود).', max_length=10, null=True, unique=True, verbose_name='کد معرف اختصاصی')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, help_text='موجودی دلاری که کاربر می\u200cتواند درخواست برداشت دهد.', max_digits=20, verbose_name='موجودی نقدی (قابل برداشت)')),
                ('reinvest_balance', models.DecimalField(decimal_places=2, default=0, help_text='موجودی که فقط برای خرید پلن قابل استفاده است.', max_digits=20, verbose_name='موجودی سرمایه\u200cگذاری مجدد')),
                ('crypto_wallet_address', models.CharField(blank=True, help_text='آدرس اختصاصی تولید شده برای واریزهای کاربر.', max_length=255, null=True, unique=True, verbose_name='آدرس کیف پول تتر (واریز)')),
                ('crypto_address_index', models.PositiveIntegerField(blank=True, help_text='⚠️ فنی: شماره ردیف در کیف پول مادر. دستی تغییر ندهید.', null=True, verbose_name='ایندکس HD Wallet')),
                ('lottery_points', models.IntegerField(default=0, verbose_name='امتیاز لاتاری')),
                ('auto_compound', models.BooleanField(default=False, help_text='اگر فعال باشد، سود روزانه به جای کیف پول، به اصل سرمایه اضافه می\u200cشود.', verbose_name='سود مرکب خودکار (Auto Compound)')),
                ('binary_position', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True)),
                ('left_volume', models.DecimalField(decimal_places=2, default=0, help_text='امتیازهای جمع شده در تیم چپ (هنوز تسویه نشده).', max_digits=20, verbose_name='حجم فروش سمت چپ')),
                ('right_volume', models.DecimalField(decimal_places=2, default=0, help_text='امتیازهای جمع شده در تیم راست (هنوز تسویه نشده).', max_digits=20, verbose_name='حجم فروش سمت راست')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, help_text='مجموع تمام کمیسیون\u200cهای دریافتی تا این لحظه.', max_digits=20, verbose_name='کل درآمد کسب شده')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='تراز کل (Legacy)')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BinaryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_volume', models.DecimalField(decimal_places=2, help_text='حجمی که در هر دو طرف وجود داشت و تسویه شد.', max_digits=20, verbose_name='حجم تعادل (Match)')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد اعمال شده')),
                ('calc_amount', models.DecimalField(decimal_places=2, default=0, help_text='سود کل قبل از اعمال سقف درآمد.', max_digits=20, verbose_name='سود محاسباتی (خام)')),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='مبلغ نهایی واریز شده به کیف پول.', max_digits=20, verbose_name='سود پرداخت شده')),
                ('flushed_amount', models.DecimalField(decimal_places=2, default=0, help_text='🔥 مبلغی که به دلیل سقف درآمد روزانه به کاربر تعلق نگرفت.', max_digits=20, verbose_name='سود سوخت شده (Flush)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ محاسبه')),
            ],
            options={
                'verbose_name': 'گزارش کمیسیون باینری',
                'verbose_name_plural': 'گزارشات کمیسیون باینری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مقدار سوخت شده')),
                ('reason', models.CharField(choices=[('daily_cap', 'Daily Cap Exceeded'), ('total_cap', 'Total Plan Cap Reached'), ('no_active_plan', 'No Active Plan')], max_length=20, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درآمد سوخت شده',
                'verbose_name_plural': 'لیست درآمدهای سوخت شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelCommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='سطح (Level)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ پورسانت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ واریز')),
            ],
            options={
                'verbose_name': 'تاریخچه کمیسیون سطحی',
                'verbose_name_plural': 'تاریخچه کمیسیون\u200cهای سطحی',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USDT', 'Tether (USDT-TRC20)'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('TRX', 'Tron')], default='USDT', max_length=10, verbose_name='نوع ارز پرداختی')),
                ('txid_or_hash', models.CharField(blank=True, help_text='کد تراکنش از بلاکچین (اختیاری)', max_length=255, null=True, verbose_name='Transaction ID / Hash')),
                ('receipt_image', models.ImageField(blank=True, help_text='اسکرین\u200cشات از تراکنش یا رسید بانکی', null=True, upload_to='payment_receipts/%Y/%m/%d/', verbose_name='تصویر رسید پرداخت')),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, help_text='⚠️ ادمین: مبلغ واقعی دریافتی را وارد کنید', max_digits=20, null=True, verbose_name='💰 مبلغ تأیید شده (USD)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('admin_notes', models.TextField(blank=True, help_text='توضیحات برای سایر ادمین\u200cها (کاربر نمی\u200cبیند)', null=True, verbose_name='یادداشت ادمین (داخلی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد درخواست')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی ادمین')),
            ],
            options={
                'verbose_name': '💳 درخواست واریز',
                'verbose_name_plural': '💳 درخواست\u200cهای واریز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_referral_required', models.BooleanField(default=True, verbose_name='کد معرف اجباری باشد')),
                ('is_email_required', models.BooleanField(default=False, verbose_name='ایمیل اجباری باشد')),
                ('is_mobile_required', models.BooleanField(default=True, verbose_name='موبایل اجباری باشد')),
            ],
            options={
                'verbose_name': 'تنظیمات ثبت نام',
                'verbose_name_plural': 'تنظیمات ثبت نام',
            },
        ),
        migrations.CreateModel(
            name='ROIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ سود')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد اعمال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ واریز')),
            ],
            options={
                'verbose_name': 'تاریخچه سود روزانه (ROI)',
                'verbose_name_plural': 'تاریخچه سودهای روزانه',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ اصل سرمایه')),
                ('accumulated_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='سود انباشته شده')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فعال\u200cسازی')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'پلن فعال کاربر',
                'verbose_name_plural': 'پلن\u200cهای فعال کاربران',
            },
        ),
    ]
