# Generated by Django 4.2.7 on 2026-02-07 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.investmentplan', verbose_name='پلن انتخابی'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_plan', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='roihistory',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investmentplan', verbose_name='پلن مرتبط'),
        ),
        migrations.AddField(
            model_name='roihistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_histories', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='plan',
            field=models.ForeignKey(help_text='پلنی که کاربر قصد خرید آن را دارد', on_delete=django.db.models.deletion.PROTECT, to='investments.investmentplan', verbose_name='پلن انتخابی'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='related_investment',
            field=models.OneToOneField(blank=True, help_text='🔗 لینک به Investment که از این Payment ساخته شد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_source', to='investments.userinvestment', verbose_name='سرمایه\u200cگذاری ایجاد شده'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='levelcommissionhistory',
            name='earner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_commissions', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده'),
        ),
        migrations.AddField(
            model_name='levelcommissionhistory',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_level_commissions', to=settings.AUTH_USER_MODEL, verbose_name='بابت کاربر (منشاء)'),
        ),
        migrations.AddField(
            model_name='burnedincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned_incomes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='binarycommission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_commissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='binary_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binary_children', to=settings.AUTH_USER_MODEL, verbose_name='والد باینری'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='شخصی که این کاربر را مستقیماً دعوت کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='معرف مستقیم (Direct)'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='roihistory',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ro_user_id_66997d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['user', 'status'], name='accounts_pa_user_id_e37843_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_pa_status_249125_idx'),
        ),
        migrations.AddIndex(
            model_name='levelcommissionhistory',
            index=models.Index(fields=['earner', 'created_at'], name='accounts_le_earner__0926b3_idx'),
        ),
    ]
