# Generated by Django 4.2.7 on 2026-02-07 18:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='برای پلن\u200cهایی که درصد مخصوص ندارند', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد کمیسیون باینری پیش\u200cفرض')),
                ('binary_match_type', models.CharField(choices=[('weak_leg', 'پای ضعیف (Weak Leg)'), ('both_legs', 'هر دو پا')], default='weak_leg', max_length=20, verbose_name='نوع محاسبه باینری')),
                ('binary_carry_forward', models.BooleanField(default=True, help_text='آیا حجم باقیمانده به روز بعد منتقل شود؟', verbose_name='انتقال حجم اضافی به روز بعد')),
                ('max_level_depth', models.PositiveIntegerField(default=10, help_text='تا چند سطح به بالا کمیسیون پرداخت شود', validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر عمق سطح\u200cبندی')),
                ('level_commission_from', models.CharField(choices=[('plan_price', 'قیمت پلن'), ('binary_commission', 'کمیسیون باینری')], default='plan_price', help_text='کمیسیون سطح از کدام مبلغ محاسبه شود', max_length=20, verbose_name='پایه محاسبه کمیسیون سطح')),
                ('roi_payment_time', models.TimeField(default='00:00:00', verbose_name='ساعت پرداخت ROI روزانه')),
                ('roi_payment_on_weekends', models.BooleanField(default=True, help_text='آیا ROI در روزهای شنبه و جمعه پرداخت شود؟', verbose_name='پرداخت ROI در تعطیلات')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='در این حالت کاربران نمی\u200cتوانند خرید/برداشت انجام دهند', verbose_name='حالت تعمیرات')),
                ('maintenance_message', models.TextField(blank=True, null=True, verbose_name='پیام حالت تعمیرات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات MLM',
                'verbose_name_plural': 'تنظیمات MLM',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='حداقل مبلغ برداشت')),
                ('max_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='حداکثر مبلغ برداشت (در هر درخواست)')),
                ('withdrawal_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد کارمزد برداشت')),
                ('withdrawal_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='علاوه بر درصد، یک مبلغ ثابت نیز کسر می\u200cشود', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='کارمزد ثابت برداشت')),
                ('daily_withdrawal_limit', models.PositiveIntegerField(default=3, help_text='0 = نامحدود', verbose_name='محدودیت تعداد برداشت روزانه')),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='درخواست\u200cهای زیر این مبلغ به صورت خودکار تأیید می\u200cشوند (0 = غیرفعال)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='آستانه تأیید خودکار')),
                ('withdrawal_processing_days', models.PositiveIntegerField(default=3, verbose_name='مدت زمان پردازش برداشت (روز کاری)')),
            ],
            options={
                'verbose_name': 'تنظیمات برداشت',
                'verbose_name_plural': 'تنظیمات برداشت',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پلن')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت پلن (USDT)')),
                ('binary_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='حجمی که این پلن در ساختار باینری والد تولید می\u200cکند', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='حجم باینری تولیدی')),
                ('binary_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='اگر 0 باشد، از تنظیمات کلی MLM استفاده می\u200cشود', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد کمیسیون باینری')),
                ('daily_binary_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='حداکثر سود باینری قابل دریافت در روز (0 = نامحدود)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سقف سود روزانه باینری')),
                ('roi_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='سود ثابت ماهیانه (0 = بدون ROI)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد سود ماهیانه ROI')),
                ('roi_duration_days', models.PositiveIntegerField(default=365, help_text='تعداد روزهایی که ROI پرداخت می\u200cشود', verbose_name='مدت زمان ROI (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پلن سرمایه\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای سرمایه\u200cگذاری',
                'ordering': ['order', 'price'],
                'indexes': [models.Index(fields=['is_active', 'price'], name='core_plan_is_acti_11f325_idx')],
            },
        ),
        migrations.CreateModel(
            name='LevelCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره سطح')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='درصد کمیسیون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیمات کمیسیون سطح',
                'verbose_name_plural': 'تنظیمات کمیسیون سطوح',
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='core_levelc_level_3578d7_idx')],
            },
        ),
    ]
