# Generated by Django 4.2.7 on 2026-02-07 18:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی قابل برداشت کاربر', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی نقدی')),
                ('investment_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='سود حاصل از ROI که به موجودی نقدی منتقل می\u200cشود', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی سرمایه\u200cگذاری')),
                ('commission_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='کمیسیون\u200cهای دریافتی از سیستم باینری و سطوح', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی کمیسیون')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجودی در انتظار تایید برداشت', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی قفل\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('roi', 'سود روزانه'), ('commission_binary', 'کمیسیون باینری'), ('commission_level', 'کمیسیون سطح'), ('investment', 'سرمایه\u200cگذاری'), ('investment_return', 'بازگشت سرمایه'), ('refund', 'بازگشت وجه'), ('transfer', 'انتقال')], max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('reference_id', models.CharField(blank=True, help_text='شناسه یکتا برای پیگیری تراکنش', max_length=100, verbose_name='شناسه مرجع')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='حداقل مبلغ برداشت: 10,000 تومان', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('10000.00'))], verbose_name='مبلغ درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('bank_account', models.CharField(help_text='شماره حساب بانکی بدون خط تیره', max_length=20, verbose_name='شماره حساب')),
                ('bank_card', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت')),
                ('account_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('user_description', models.TextField(blank=True, verbose_name='توضیحات کاربر')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد درخواست')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیگیری پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='withdrawal__wallet__43a982_idx'), models.Index(fields=['status', '-created_at'], name='withdrawal__status_e67567_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__efd4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='transaction_transac_a32e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='transaction_referen_897c8a_idx'),
        ),
    ]
