# Generated by Django 4.2.7 on 2026-02-07 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('jackpot_carry_over', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pot', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('participants_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LotterySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('jackpot_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('lottery_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lottery.lotteryround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('lottery_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.lotteryround')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.lotteryticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
